// Curated personal catalog - ONLY these series exist in the app (owner's list, 2026-09-16).
// Resolved against WeebCentral; id = '{ULID}/{Slug}' for the 'kakalot' source. Entries
// flagged unavailable are not on WeebCentral (kept greyed so the list stays complete).
// To add series: append here (resolve id via /scrape?site=kakalot&action=search).

export interface CatalogEntry {
  title: string
  id: string
  wcTitle: string
  cover?: string       // explicit proxied cover (Comizy 'buddy:' entries); WC covers are derived from the id
  unavailable?: boolean
}

export const CATALOG: CatalogEntry[] = [
  {"title":"Omniscient Reader\u0027s Viewpoint","id":"01J76XYDMWWJX3T4BFWR84FQQK/Omniscient-Readers-Viewpoint","wcTitle":"Omniscient Reader"},
  {"title":"The Greatest Estate Developer","id":"01J76XYF6V9BDFSRRTY2C65SBS/The-Greatest-Estate-Developer","wcTitle":"The Greatest Estate Developer"},
  {"title":"Tower of God","id":"01J76XY7M0W9WWJ55VJYYB2J1S/Tower-Of-God","wcTitle":"Tower of God"},
  {"title":"The Beginning After the End","id":"01J76XYE23859ZWDP7BJ520AKY/The-Beginning-After-The-End","wcTitle":"The Beginning After the End"},
  {"title":"The Boxer","id":"01J76XYE1AGN5RA226EAQ703MW/The-Boxer","wcTitle":"The Boxer"},
  {"title":"Solo Leveling","id":"01J76XYCPSY3C4BNPBRY8JMCBE/Solo-Leveling","wcTitle":"Solo Leveling"},
  {"title":"Legend of the Northern Blade","id":"01J76XYDT27VJHNB59FJR01G7S/Legend-of-the-Northern-Blade","wcTitle":"The Legend of the Northern Blade"},
  {"title":"SSS-Class Revival Hunter","id":"01J76XYEADS8EDBWFPVSF8J3VG/SSS-Class-Suicide-Hunter","wcTitle":"SSS-Class Revival Hunter"},
  {"title":"Return of the Blossoming Blade","id":"01J76XYEVCSS5ANBCJZ4ZF9P65/Return-of-the-Blossoming-Blade","wcTitle":"Return of the Blossoming Blade"},
  {"title":"Bastard","id":"01J76XYBJC4C66DDZYVS2PHVRW/Bastard","wcTitle":"Bastard"},
  {"title":"The World After the Fall","id":"01J76XYFA2SNRMQT60JEWDRZRW/The-World-After-the-Fall","wcTitle":"The World After the Fall"},
  {"title":"Eleceed","id":"01J76XYD3Q2Q7HYYMB3FSDPSKC/Eleceed","wcTitle":"Eleceed"},
  {"title":"Nano Machine","id":"01J76XYDT7H7ANER8KJG5R9SJV/Nano-Machine","wcTitle":"Nano Machine"},
  {"title":"The Ember Knight","id":"01J76XYEVH4687SJ1FY602R4JP/The-Ember-Knight","wcTitle":"The Ember Knight"},
  {"title":"Lookism","id":"01J76XYBD282Y3XKX0KRGD64Q5/Lookism","wcTitle":"Lookism"},
  {"title":"Sweet Home","id":"01J76XYD408AB9GAJGGK2Z25S6/Sweet-Home","wcTitle":"Sweet Home"},
  {"title":"Weak Hero","id":"01J76XYD43SVADEPB6HPG5TZDH/Weak-Hero","wcTitle":"Weak Hero"},
  {"title":"The Breaker","id":"01J76XY7GSC6DZ9HPGAJ6TCC3Q/The-Breaker","wcTitle":"The Breaker"},
  {"title":"Doom Breaker","id":"01J76XYEZ1BQJM22H3RREE1XMG/Doom-Breaker","wcTitle":"Doom Breaker"},
  {"title":"Murim Login","id":"01J76XYE0NQJN87JW5VZNAQG70/Murim-Login","wcTitle":"Murim Login"},
  {"title":"Pick Me Up, Infinite Gacha","id":"01J76XYGY7FDV857J4HJAZ131K/Pick-Me-Up-Infinite-Gacha","wcTitle":"Pick Me Up, Infinite Gacha"},
  {"title":"Infinite Mage","id":"01JRZATJ2P56YN7DNT6CXQBMEN/the-infinite-mage","wcTitle":"The Infinite Mage"},
  {"title":"The Dark Swordsman Returns","id":"01JZZAYVMTGH10GPR8RP3K1TN5/the-dark-swordsman-returns","wcTitle":"The Dark Swordsman Returns"},
  {"title":"The Novel\u0027s Extra","id":"01J76XYG8EFP7X07BC3KCDCS37/The-Novels-Extra","wcTitle":"The Novel\u0027s Extra (2022)"},
  {"title":"Return of the Disaster-Class Hero","id":"01J76XYF85TPSFGEH5GCC1VWAW/Return-of-the-Disaster-Class-Hero","wcTitle":"The Return of the Disaster-Class Hero"},
  {"title":"Return of the Crazy Demon","id":"01J76XYF02HVMZAMXFFS51ANAM/The-Return-of-the-Crazy-Demon","wcTitle":"Return of the Mad Demon"},
  {"title":"The Heavenly Demon Can\u0027t Live a Normal Life","id":"01J76XYGCJ0NXBK4MYAJ5YKPH3/Descended-from-Divinity","wcTitle":"Descended from Divinity"},
  {"title":"S-Classes That I Raised","id":"01J76XYF7BM7346K02H8VBKYBX/The-S-Classes-That-I-Raised","wcTitle":"My S-Class Hunters"},
  {"title":"Extra\u0027s Academy Survival Guide","id":"01JNKH97S0APRHFW53V9DSFCGH/The-Extras-Academy-Survival-Guide","wcTitle":"Extra\u0027s Academy Survival Guide"},
  {"title":"Academy\u0027s Undercover Professor","id":"01J76XYFQBDVR1HQ759MGFK2E9/The-Academys-Undercover-Professor","wcTitle":"Academy\u0027s Undercover Professor"},
  {"title":"Academy\u0027s Genius Swordsman","id":"01J76XYH4MDDX3ZT2NA0HJN20Y/The-Academys-Genius-Swordsman","wcTitle":"Academy\u0027s Genius Swordsman"},
  {"title":"The Player Hides His Past","id":"01JW12YERG2DXWS8AY2ADCQA58/the-player-hides-his-past","wcTitle":"The Player Hides His Past"},
  {"title":"Lazy Lord Masters the Sword","id":"01J76XYEZWRB4MRT7EHVVPEDXV/Reformation-of-the-Deadbeat-Noble","wcTitle":"The Lazy Lord Masters the Sword"},
  {"title":"Leveling Up With the Gods","id":"01J76XYF1SE3KTV7YEV5WD9Z86/Level-Up-with-the-Gods","wcTitle":"Leveling Up With the Gods"},
  {"title":"Infinite Leveling: Murim","id":"01J76XYESZW6RJD0T705G7W34J/Infinite-Leveling-Murim","wcTitle":"Infinite Leveling: Murim"},
  {"title":"The Regressed Mercenary Has a Plan","id":"01JNKHGT37KPS3KBVA5CG1X7V0/the-regressed-mercenary-has-a-plan","wcTitle":"The Regressed Mercenary Has a Plan"},
  {"title":"Dark Mage\u0027s Return to Enlistment","id":"01M02S4TGF866VH7MPCA9WJ37J/The-Dark-Mages-Return-to-Enlistment","wcTitle":"Dark Mage\u0027s Return to Enlistment"},
  {"title":"Swordmaster\u0027s Youngest Son","id":"01J76XYG8FNWRR3PHEFKN2NB87/The-Swordmasters-Son","wcTitle":"Swordmaster\u0027s Youngest Son"},
  {"title":"Return of the Shattered Constellation","id":"buddy:kNxgKvOE:return-of-the-shattered-constellation","wcTitle":"Return Of The Shattered Constellation","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2F85a96a6cba78.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Indomitable Martial King","id":"01JRZBAVB829AKGARECHF5QWYR/the-reincarnated-king-of-fists","wcTitle":"The Reincarnated King of Fists"},
  {"title":"Lone Necromancer","id":"01J76XYF7A7W131X37XKCGKWZ7/Solo-Necromancy","wcTitle":"The Lone Necromancer"},
  {"title":"Max-Level Player\u0027s 100th Regression","id":"01K27G582KZJ5TPCJ5K83MSPX4/the-100th-regression-of-the-maxlevel-player","wcTitle":"The 100th Regression of the Max-Level Player"},
  {"title":"I\u0027m the Max-Level Newbie","id":"01J76XYEZYBE7Y3MEY7AEQ8MQN/Solo-Max-Level-Newbie","wcTitle":"I\u0027m the Max-Level Newbie"},
  {"title":"A Returner\u0027s Magic Should Be Special","id":"01J76XYCN4PDFA5CZQXHK82PXD/A-Returners-Magic-Should-Be-Special","wcTitle":"A Returner\u0027s Magic Should Be Special"},
  {"title":"The Great Mage Returns After 4000 Years","id":"01J76XYDMTRNJZJH9G1ADMPJQC/The-Great-Mage-Returns-After-4000-Years","wcTitle":"The Archmage Returns After 4000 Years"},
  {"title":"Skeleton Soldier Failed to Defend the Dungeon","id":"01J76XYCRFYM9JT9WE2M8Q6D6T/Skeleton-Soldier-Couldnt-Protect-The-Dungeon","wcTitle":"The Skeleton Soldier Failed to Defend the Dungeon"},
  {"title":"Trash of the Count\u0027s Family","id":"01J76XYE153CVDWZ5JB5VGGB2M/Trash-of-the-Counts-Family","wcTitle":"Lout of Count\u0027s Family"},
  {"title":"Eternally Regressing Knight","id":"01JCZQE424026XN50GCNGS5AG0/the-knight-who-only-lives-today","wcTitle":"The Knight Only Lives Today"},
  {"title":"Gosu","id":"01J76XYBJPAT812D7XKBZQVRHA/Gosu-The-Master","wcTitle":"GOSU"},
  {"title":"Second Life Ranker","id":"01J76XYDMS2ZM3HF00619R92NJ/Second-Life-Ranker","wcTitle":"Second Life Ranker"},
  {"title":"The God of High School","id":"01J76XY7KZX4EHBWNQYAB02T91/The-God-Of-High-School","wcTitle":"The God of High School"},
  {"title":"Hardcore Leveling Warrior","id":"01J76XYBPH622HYFF8K397PYR7/Hardcore-Leveling-Warrior","wcTitle":"Hardcore Leveling Warrior"},
  {"title":"Mercenary Enrollment","id":"01J76XYEA95PG5AVMCKC9TK492/Mercenary-Enrollment","wcTitle":"Teenage Mercenary"},
  {"title":"Wind Breaker","id":"01J76XYA1TQYKV6W4BCMR2WD5M/Wind-Breaker","wcTitle":"Wind Breaker"},
  {"title":"Viral Hit","id":"01J76XYE8HKQ5KFPY5MRR9CNCR/Viral-Hit","wcTitle":"Viral Hit"},
  {"title":"Study Group","id":"01J76XYEAEV8AGB1HTG3HTYH1W/Study-Group","wcTitle":"Study Group"},
  {"title":"Manager Kim","id":"01J76XYFACRRYCNNV6H48PMYDA/Manager-Kim","wcTitle":"Manager Kim"},
  {"title":"Jungle Juice","id":"01J76XYEFZDGY0JV4Y6RGM23T3/Jungle-Juice","wcTitle":"Jungle Juice"},
  {"title":"Reality Quest","id":"01JRT72TAZ1SWHWXKTJ4ZX3QE3/reality-quest","wcTitle":"Reality Quest"},
  {"title":"Questism","id":"01J76XYF8N9H3DZVGT3SRHJ48D/QUESTISM","wcTitle":"QUESTISM"},
  {"title":"The Advanced Player of the Tutorial Tower","id":"01J76XYE104QJZC9KZK8CEEGWE/The-Tutorial-Towers-Advanced-Player","wcTitle":"The Advanced Player of the Tutorial Tower"},
  {"title":"Return to Player","id":"01J76XYEACR3847BBQHP5F6W0H/Return-to-Player","wcTitle":"Return to Player"},
  {"title":"Kill the Hero","id":"01J76XYDT1AA48EB98JNQPPGBD/Kill-The-Hero","wcTitle":"Kill The Hero"},
  {"title":"Dungeon Reset","id":"01J76XYE0BQF9Y40B2BH26RKZS/Dungeon-Reset","wcTitle":"Dungeon Reset"},
  {"title":"Overgeared","id":"01J76XYDMR2777KEM5BKTBBK83/Overgeared","wcTitle":"Overgeared"},
  {"title":"The Tutorial Is Too Hard","id":"01J76XYEGRA8FZJD7V4HVH6E4J/The-Tutorial-is-Too-Hard","wcTitle":"The Tutorial is Too Tough"},
  {"title":"Player Who Returned 10,000 Years Later","id":"01J76XYG0RMDGG2PXJPXNE3XDM/After-Ten-Millennia-in-Hell","wcTitle":"After Ten Millennia in Hell"},
  {"title":"The Constellation That Returned From Hell","id":"01J76XYEK495NWYX42PF2APZGE/The-Constellation-that-Returned-from-Hell","wcTitle":"The Celestial Returned from Hell"},
  {"title":"The Second Coming of Gluttony","id":"01J76XYD5GP66R7CWDY075X5YE/The-Second-Coming-of-Gluttony","wcTitle":"The Second Coming of Gluttony"},
  {"title":"Volcanic Age","id":"01J76XYCDPJ3GN1NTE11GS9TEV/Volcanic-Age","wcTitle":"Volcanic Age"},
  {"title":"Chronicles of the Heavenly Demon","id":"01J76XYDN566GKDS5C2KHHQPK3/Heavenly-Demon-Reborn","wcTitle":"Chronicles of the Heavenly Demon"},
  {"title":"Memoir of the King of War","id":"buddy:x5XEXmj1:memoir-of-the-king-of-war","wcTitle":"Memoir Of The King Of War","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2Fae63fc7a7538.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Fist Demon of Mount Hua","id":"buddy:X5rv225Q:fist-demon-of-mount-hua","wcTitle":"Fist Demon Of Mount Hua","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2F6c8214e44b6d.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Peerless Dad","id":"01J76XYCXXB105QEZ4J82JBAEB/Peerless-Dad","wcTitle":"Father, Unrivaled"},
  {"title":"Legend of Asura: The Venom Dragon","id":"01J76XYEG043VFH182TS4CCFYE/Legend-of-Asura-The-Venom-Dragon","wcTitle":"Legend of Asura - The Venom Dragon"},
  {"title":"Absolute Sword Sense","id":"01JJ2D2B46DZ8QYPVGNVC63V3E/absolute-sword-sense","wcTitle":"Absolute Sword Sense"},
  {"title":"Myst, Might, Mayhem","id":"01JGBZG1YMHNV78HCA29ZFZXWD/myst-might-mayhem","wcTitle":"Myst, Might, Mayhem"},
  {"title":"Revenge of the Iron-Blooded Sword Hound","id":"01J76XYG95PJHF8P3PGVKJT5NQ/Revenge-of-the-Baskerville-Bloodhound","wcTitle":"Revenge of the Iron-Blooded Sword Hound"},
  {"title":"Surviving the Game as a Barbarian","id":"01J76XYG976314R2DM2DKQRBGS/Surviving-The-Game-as-a-Barbarian","wcTitle":"Surviving the Game as a Barbarian"},
  {"title":"Dungeon Odyssey","id":"01JNKGRKJ61H73S8M5CKZ5FKWD/dungeon-odyssey","wcTitle":"Dungeon Odyssey"},
  {"title":"The Stellar Swordmaster","id":"01JJCB7T8DYSR86CMK1ZYPCN7A/the-stellar-swordmaster","wcTitle":"The Stellar Swordmaster"},
  {"title":"The Demon Prince Goes to the Academy","id":"buddy:Y5lKYlNl:the-demon-prince-goes-to-the-academy","wcTitle":"The Demon Prince goes to the Academy","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2Ffeddcf17c2c1.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Tyrant of the Tower Defense Game","id":"01JS1VSEVMC4FVSDACKNWY5E1H/tyrant-of-the-tower-defense-game","wcTitle":"Tyrant of the Tower Defense Game"},
  {"title":"Star-Embracing Swordmaster","id":"buddy:mOqQ9aOR:star-embracing-swordmaster","wcTitle":"Star-Embracing Swordmaster","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2Fe6eb345e257d.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Absolute Regression","id":"01JGBYTDYCGFHJCQ16JBW69SZB/absolute-regression","wcTitle":"Absolute Regression"},
  {"title":"Villains Are Destined to Die","id":"01J76XYDMZ059WG12B0QQWRYXS/Death-Is-the-Only-Ending-for-the-Villainess","wcTitle":"Villains Are Destined to Die"},
  {"title":"Who Made Me a Princess","id":"01J76XYDQPCQQR5DQXXF8NHKWK/Who-Made-Me-A-Princess","wcTitle":"Who Made Me A Princess"},
  {"title":"The Remarried Empress","id":"01J76XYE0QZF764D2B2ZNPXF95/Remarried-Empress","wcTitle":"The Remarried Empress"},
  {"title":"The Horizon","id":"01J76XYEAG9DM7NCYEWEYBH9AV/The-Horizon","wcTitle":"The Horizon"},
  {"title":"Pigpen","id":"01J76XYGXRHTJ8JP6AYMBB57CZ/PIGPEN","wcTitle":"PIGPEN"},
  {"title":"Shotgun Boy","id":"01J76XYEHPSTBZVNFJDCCRQH7P/Shotgun-Boy","wcTitle":"Shotgun Boy"},
  {"title":"Dr. Frost","id":"01J76XY8EMS37BK2PDFXH0NMZE/Dr-Frost","wcTitle":"Dr. Frost"},
  {"title":"Kubera","id":"01J76XY7P3BCR7KJ37JYTBC42X/Kubera","wcTitle":"Kubera"},
  {"title":"Purple Hyacinth","id":"buddy:L5MbZgjl:purple-hyacinth","wcTitle":"Purple Hyacinth","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2Fe9d697262f7e.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Seasons of Blossom","id":"01J76XYEMAHA9EF4V936RPKPCG/Seasons-of-Blossom","wcTitle":"Seasons of Blossom"},
  {"title":"Annarasumanara","id":"01J76XY8J2X7XNA2KE7DTGE319/Annarasumanara","wcTitle":"Annarasumanara"},
  {"title":"Noblesse","id":"01J76XY7KS655DGFQEVH9DPSGX/Noblesse","wcTitle":"Noblesse"},
  {"title":"Dice","id":"01J76XY8T2JH0M0DMYBQ2ZTSJG/DICE","wcTitle":"Dice"},
  {"title":"The Investor Who Sees the Future","id":"buddy:zj2qwX5M:the-investor-who-sees-the-future","wcTitle":"The Investor Who Sees the Future","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2Fa92e2448c373.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Super Gene","id":"buddy:Gj7042Ov:super-gene","wcTitle":"Super Gene","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2F6e99a956cfff.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
  {"title":"Global Freeze: I Created An Apocalypse Shelter","id":"buddy:RO60Vk5w:global-freeze-i-created-an-apocalypse-shelter","wcTitle":"Global Freeze: I Created An Apocalypse Shelter","cover":"https://yomu-image-proxy.subramanya-bellary.workers.dev/scrape?site=kakalot&action=img&u=https%3A%2F%2Frx.comizy.io%2Fcovers%2Fc4b848eea950.webp&ref=https%3A%2F%2Fcomizy.io%2F"},
]
